
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.infracast.schemas.managedtext.v10_2;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-04-15T15:36:04.421+01:00
 * Generated source version: 2.7.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "EmxService",
                      portName = "EmxServiceSoap12",
                      targetNamespace = "http://www.infracast.com/schemas/managedtext/v10_2",
                      wsdlLocation = "sms.wsdl",
                      endpointInterface = "com.infracast.schemas.managedtext.v10_2.EmxServiceSoap")
                      
public class EmxServiceSoapImpl implements EmxServiceSoap {

    private static final Logger LOG = Logger.getLogger(EmxServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.infracast.schemas.managedtext.v10_2.EmxServiceSoap#sendSMS(com.infracast.schemas.emx.v10_2.EmxSendSmsRequest  sendSmsRequest )*
     */
    public com.infracast.schemas.emx.v10_2.EmxSendSmsResponse sendSMS(com.infracast.schemas.emx.v10_2.EmxSendSmsRequest sendSmsRequest) { 
        LOG.info("Executing operation sendSMS");
        System.out.println(sendSmsRequest);
        try {
        	 com.infracast.schemas.emx.v10_2.EmxSendSmsResponse _return = new com.infracast.schemas.emx.v10_2.EmxSendSmsResponse();
             com.infracast.schemas.managedtext.v10_2.EmxStatus status=new com.infracast.schemas.managedtext.v10_2.EmxStatus();
             status.setCode("1");
             status.setText("2");
             status.setValue(3);
             _return.setStatus(status);
             return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infracast.schemas.managedtext.v10_2.EmxServiceSoap#smsNotification(com.infracast.schemas.emx.v10_2.EmxSMSNotificationRequest  smsNotificationRequest )*
     */
    public com.infracast.schemas.emx.v10_2.EmxSMSNotificationResponse smsNotification(com.infracast.schemas.emx.v10_2.EmxSMSNotificationRequest smsNotificationRequest) { 
        LOG.info("Executing operation smsNotification");
        System.out.println(smsNotificationRequest);
        try {
            com.infracast.schemas.emx.v10_2.EmxSMSNotificationResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infracast.schemas.managedtext.v10_2.EmxServiceSoap#ping(com.infracast.schemas.emx.v10_2.EmxPingRequest  pingRequest )*
     */
    public com.infracast.schemas.emx.v10_2.EmxPingResponse ping(com.infracast.schemas.emx.v10_2.EmxPingRequest pingRequest) { 
        LOG.info("Executing operation ping");
        System.out.println(pingRequest);
        try {
            com.infracast.schemas.emx.v10_2.EmxPingResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infracast.schemas.managedtext.v10_2.EmxServiceSoap#sendVoice(com.infracast.schemas.emx.v10_2.EmxSendVoiceRequest  sendVoiceRequest )*
     */
    public com.infracast.schemas.emx.v10_2.EmxSendVoiceResponse sendVoice(com.infracast.schemas.emx.v10_2.EmxSendVoiceRequest sendVoiceRequest) { 
        LOG.info("Executing operation sendVoice");
        System.out.println(sendVoiceRequest);
        try {
            com.infracast.schemas.emx.v10_2.EmxSendVoiceResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
