package com.infracast.schemas.managedtext.v10_2;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-04-15T15:36:04.500+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "EmxService", 
                  wsdlLocation = "sms.wsdl",
                  targetNamespace = "http://www.infracast.com/schemas/managedtext/v10_2") 
public class EmxService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.infracast.com/schemas/managedtext/v10_2", "EmxService");
    public final static QName EmxServiceSoap12 = new QName("http://www.infracast.com/schemas/managedtext/v10_2", "EmxServiceSoap12");
    public final static QName EmxServiceSoap = new QName("http://www.infracast.com/schemas/managedtext/v10_2", "EmxServiceSoap");
    static {
        URL url = EmxService.class.getResource("sms.wsdl");
        if (url == null) {
            url = EmxService.class.getClassLoader().getResource("sms.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(EmxService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "sms.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public EmxService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmxService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmxService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmxService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmxService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmxService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EmxServiceSoap
     */
    @WebEndpoint(name = "EmxServiceSoap12")
    public EmxServiceSoap getEmxServiceSoap12() {
        return super.getPort(EmxServiceSoap12, EmxServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmxServiceSoap
     */
    @WebEndpoint(name = "EmxServiceSoap12")
    public EmxServiceSoap getEmxServiceSoap12(WebServiceFeature... features) {
        return super.getPort(EmxServiceSoap12, EmxServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns EmxServiceSoap
     */
    @WebEndpoint(name = "EmxServiceSoap")
    public EmxServiceSoap getEmxServiceSoap() {
        return super.getPort(EmxServiceSoap, EmxServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmxServiceSoap
     */
    @WebEndpoint(name = "EmxServiceSoap")
    public EmxServiceSoap getEmxServiceSoap(WebServiceFeature... features) {
        return super.getPort(EmxServiceSoap, EmxServiceSoap.class, features);
    }

}
