package com.infracast.schemas.managedtext.v10_2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-04-15T15:36:04.488+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.infracast.com/schemas/managedtext/v10_2", name = "EmxServiceSoap")
@XmlSeeAlso({ObjectFactory.class, com.infracast.schemas.emx.v10_2.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EmxServiceSoap {

    @WebResult(name = "SendSMSResponse", targetNamespace = "http://www.infracast.com/schemas/managedtext/v10_2", partName = "SendSMSResult")
    @WebMethod(operationName = "SendSMS", action = "http://localhost:8080/EmxServices/SendSMS")
    public com.infracast.schemas.emx.v10_2.EmxSendSmsResponse sendSMS(
        @WebParam(partName = "sendSmsRequest", name = "sendSmsRequest", targetNamespace = "http://www.infracast.com/schemas/managedtext/v10_2")
        com.infracast.schemas.emx.v10_2.EmxSendSmsRequest sendSmsRequest
    );

    @WebResult(name = "SMSNotification", targetNamespace = "http://www.infracast.com/schemas/managedtext/v10_2", partName = "SMSNotificationResult")
    @WebMethod(operationName = "SMSNotification", action = "http://localhost:8080/EmxServices/SMSNotification")
    public com.infracast.schemas.emx.v10_2.EmxSMSNotificationResponse smsNotification(
        @WebParam(partName = "smsNotificationRequest", name = "smsNotificationRequest", targetNamespace = "http://www.infracast.com/schemas/managedtext/v10_2")
        com.infracast.schemas.emx.v10_2.EmxSMSNotificationRequest smsNotificationRequest
    );

    @WebResult(name = "PingResponse", targetNamespace = "http://www.infracast.com/schemas/managedtext/v10_2", partName = "PingResult")
    @WebMethod(operationName = "Ping", action = "http://localhost:8080/EmxServices/Ping")
    public com.infracast.schemas.emx.v10_2.EmxPingResponse ping(
        @WebParam(partName = "pingRequest", name = "pingRequest", targetNamespace = "http://www.infracast.com/schemas/managedtext/v10_2")
        com.infracast.schemas.emx.v10_2.EmxPingRequest pingRequest
    );

    @WebResult(name = "SendVoiceResponse", targetNamespace = "http://www.infracast.com/schemas/managedtext/v10_2", partName = "SendVoiceResult")
    @WebMethod(operationName = "SendVoice", action = "http://localhost:8080/EmxServices/SendVoice")
    public com.infracast.schemas.emx.v10_2.EmxSendVoiceResponse sendVoice(
        @WebParam(partName = "sendVoiceRequest", name = "sendVoiceRequest", targetNamespace = "http://www.infracast.com/schemas/managedtext/v10_2")
        com.infracast.schemas.emx.v10_2.EmxSendVoiceRequest sendVoiceRequest
    );
}
